# Generated by Django 3.2.2 on 2021-05-13 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 13, 16, 43, 49, 316265, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
